apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
  labels:
    app: devops-api
spec:
  type: LoadBalancer
  selector:
    app: devops-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http